export const heroItem = [
    {
        index: '1',
        bannerImg: 'https://occ-0-2433-590.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABZrkp8RvUrZVjc9GYn8-jlxnEa66xgTexL7oinRF0s2MtkbCV5CsuuRlR48sqMP0twyY46ToqL__Y3uflZ_Ln0DgZrqy6cfKas87.jpg?r=f3d',
        title: 'Người Nhện',
        year: '2002',
        type: 'Phim',
        genres: 'Hành động, viễn tưởng',
        shortDesc: 'Người Nhện là một siêu anh hùng xuất hiện trong các cuốn truyện tranh Mỹ xuất bản bởi Marvel Comics...',
    },
    {
        index: '2',
        bannerImg: 'https://2sao.vietnamnetjsc.vn/images/2023/06/23/09/01/1.jpg',
        title: 'Vụng trộm không thể giấu',
        year: '2023',
        type: 'Phim T.Hình',
        genres: 'Tình cảm, lãng mạn',
        shortDesc: 'Vụng Trộm Không Thể Giấu nói về thời trung học Tang Trĩ thường xuyên bị mời phụ huynh, để giải quyết phiền toái này cô quyết định nhờ anh trai đi hộ...',
    },
    {
        index: '3',
        bannerImg: 'https://i.ytimg.com/vi/8xVigmgvKjY/maxresdefault.jpg',
        title: 'Vùng đất linh hồn',
        year: '2001',
        type: 'Phim',
        genres: 'Kỳ ảo, Phiêu lưu',
        shortDesc: 'Sen và Chihiro ở thế giới thần bí là một bộ phim điện ảnh hoạt hình Nhật Bản đề tài tuổi mới lớn và kỳ ảo công chiếu năm 2001 do Miyazaki Hayao làm đạo diễn kiêm nhà biên kịch...',
    },
]


export const lastestUpdate = [
    {
        index: '1',
        title: "Dẫu biết",
        year: "2021",
        type: "Phim T.Hình",
        genres: "Lãng mạn",
        bannerImg: "https://thegioidienanh.vn/stores/news_dataimages/anhvu/072021/20/14/3844_03.jpg?rt=20210720144113",
        shortDesc: "Dẫu biết là một bộ phim truyền hình Hàn Quốc phát sóng năm 2021, với sự tham gia của Han So-hee, Song Kang và Chae Jong-hyeop",
        mediaId: "1",
        userId: "123",
        updated_at: "1/1/2023",
        created_at: "1/1/2023",
        watchedTime: "12h",
        episodeNumber: "8",
    },
    {
        index: '2',
        title: "Sweet Home: Thế giới ma quái",
        year: "2020",
        type: "Phim T.Hình",
        genres: "Chính kịch",
        bannerImg: "/sweethome.jpg",
        shortDesc: "Sweet Home: Thế giới ma quái là bộ phim truyền hình Hàn Quốc ra mắt năm 2020 với sự tham gia của Song Kang, Lee Jin-wook, Lee Do-hyun và Lee Si-young.",
        mediaId: "1",
        userId: "123",
        updated_at: "1/1/2023",
        created_at: "1/1/2023",
        watchedTime: "12h",
        episodeNumber: "8",
    },
    {
        index: '3',
        title: "Biệt đội siêu anh hùng: Hồi kết",
        year: "2019",
        type: "Phim",
        genres: "Hành động/Khoa học viễn tưởng",
        bannerImg: "/avg3.jpg",
        shortDesc: "Avengers: Hồi kết là phim điện ảnh siêu anh hùng Mỹ ra mắt năm 2019, do Marvel Studios sản xuất và Walt Disney Studios Motion Pictures phân phối độc quyền tại thị trường Bắc Mỹ",
        mediaId: "1",
        userId: "123",
        updated_at: "1/1/2023",
        created_at: "1/1/2023",
        watchedTime: "12h",
        episodeNumber: "8",
    },
    {
        index: '4',
        title: "Cảnh báo tình yêu",
        year: "2019",
        type: "Phim T.Hình",
        genres: "Lãng mạn",
        bannerImg: "/love-alarm.jpg",
        shortDesc: "Love Alarm là một bộ phim truyền hình Hàn Quốc drama dựa trên webtoon Daum cùng tên của Chon Kye-young. Bộ phim có sự tham gia của Kim So-hyun, Jung Ga-ram và Song Kang. Bộ phim được công chiếu trên Netflix vào ngày 22 tháng 8 năm 2019, phần 2 của bộ phim được công chiếu vào đầu năm 2021",
        mediaId: "1",
        userId: "123",
        updated_at: "1/1/2023",
        created_at: "1/1/2023",
        watchedTime: "12h",
        episodeNumber: "8",
    },
    {
        index: '1',
        title: "Dẫu biết",
        year: "2021",
        type: "Phim",
        genres: "Lãng mạn",
        bannerImg: "https://thegioidienanh.vn/stores/news_dataimages/anhvu/072021/20/14/3844_03.jpg?rt=20210720144113",
        shortDesc: "Dẫu biết là một bộ phim truyền hình Hàn Quốc phát sóng năm 2021, với sự tham gia của Han So-hee, Song Kang và Chae Jong-hyeop",
        mediaId: "1",
        userId: "123",
        updated_at: "1/1/2023",
        created_at: "1/1/2023",
        watchedTime: "12h",
        episodeNumber: "8",
    },
    {
        index: '1',
        title: "Dẫu biết",
        year: "2021",
        type: "Phim",
        genres: "Lãng mạn",
        bannerImg: "https://thegioidienanh.vn/stores/news_dataimages/anhvu/072021/20/14/3844_03.jpg?rt=20210720144113",
        shortDesc: "Dẫu biết là một bộ phim truyền hình Hàn Quốc phát sóng năm 2021, với sự tham gia của Han So-hee, Song Kang và Chae Jong-hyeop",
        mediaId: "1",
        userId: "123",
        updated_at: "1/1/2023",
        created_at: "1/1/2023",
        watchedTime: "12h",
        episodeNumber: "8",
    },
    {
        index: '1',
        title: "Dẫu biết",
        year: "2021",
        type: "Phim",
        genres: "Lãng mạn",
        bannerImg: "https://thegioidienanh.vn/stores/news_dataimages/anhvu/072021/20/14/3844_03.jpg?rt=20210720144113",
        shortDesc: "Dẫu biết là một bộ phim truyền hình Hàn Quốc phát sóng năm 2021, với sự tham gia của Han So-hee, Song Kang và Chae Jong-hyeop",
        mediaId: "1",
        userId: "123",
        updated_at: "1/1/2023",
        created_at: "1/1/2023",
        watchedTime: "12h",
        episodeNumber: "8",
    },
]